### ISSUE TITLE
ValueError: Single image generator does not exist 

### ISSUE THREAD

**Issue by linkAmy** [NVIDIA/vid2vid#104]
I am trying to use the pre-train model provided to generate more test fake_B pictures. It works well when I use this option:

> python test.py --name label2city_2048 --label_nc 35 --loadSize 2048 --n_scales_spatial 3 --fg --use_single_G 

But when I change the dataroot, here comes the error.

> python test.py --name label2city_2048 --label_nc 35 --loadSize 2048 --n_scales_spatial 3 --fg --use_single_G --dataroot _my_data_root_

the error:

> Pretrained network G0 has fewer layers; The following are not initialized:
> ['indv_down', 'indv_res', 'indv_up', 'model_down_img', 'model_down_seg', 'model_res_flow', 'model_res_img', 'model_up_flow', 'model_up_img']
> Pretrained network G1 has fewer layers; The following are not initialized:
> ['indv_down', 'indv_up', 'model_down_img', 'model_down_seg', 'model_up_flow', 'model_up_img']
> Pretrained network G2 has fewer layers; The following are not initialized:
> ['indv_down', 'indv_up', 'model_down_img', 'model_down_seg', 'model_up_flow', 'model_up_img']
> Traceback (most recent call last):
>   File "test.py", line 25, in <module>
>     model = create_model(opt)
>   File "*/vid2vid/models/models.py", line 19, in create_model
>     modelG.initialize(opt)
>   File "*/vid2vid/models/vid2vid_model_G.py", line 53, in initialize
>     self.netG_i = self.load_single_G() if self.use_single_G else None
>   File "*/vid2vid/models/vid2vid_model_G.py", line 289, in load_single_G
>     raise ValueError('Single image generator does not exist')
> ValueError: Single image generator does not exist

I use the _cityscape rightImg8bit_sequece_ test dataset and have named my new dataset folder as test_A. Note that in this folder there are several folders named by the cities and each of the city have more than one video seqence. Do I have to keep just one video sequence in a single folder?
Has anyone had this problem before?
Thanks.

**Comment by linkAmy** [comment]
It turns out that maybe I got the wrong folder name so it cannot found the pretrained generator
