### ISSUE TITLE
scripts/download_datasets.py and scripts/street/download_models.py returns a bad zip file

### ISSUE THREAD

**Issue by aschneid42** [NVIDIA/vid2vid#115]
@tcwang0509 @mingyuliutw @junyanz @mingyuliutw

Have the dataset .zip files changed, is it possible to provide a direct link to download the correct zip files?  Thanks.

Traceback (most recent call last):
  File "scripts/download_datasets.py", line 10, in <module>
    unzip_file(destination, chpt_path)
  File "C:\Projects\vid2vid-master\scripts\download_gdrive.py", line 28, in unzip_file
    zip_ref = zipfile.ZipFile(file_name, 'r')
  File "C:\Anaconda3\lib\zipfile.py", line 1108, in __init__
    self._RealGetContents()
  File "C:\Anaconda3\lib\zipfile.py", line 1175, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

**Comment by Skyrelixa** [comment]
How did this issue get resolved? I am currently facing the same problem. I've downloaded 7z in an attempt to remediate it, but it also comes back arguing the zip file is 'not an archive'. Your response would be much appreciated!!
