### ISSUE TITLE
torch.FatalError: cuda runtime error (8) : invalid device function at Resample2d_kernel.cu:205

### ISSUE THREAD

**Issue by switchhh** [NVIDIA/vid2vid#12]
I have met this problem and have no idea deal with it...
```
THCudaCheck FAIL file=Resample2d_kernel.cu line=205 error=8 : invalid device function
Traceback (most recent call last):
  File "test.py", line 43, in <module>
    generated = model.inference(A, B, inst)
  File "/mnt/yry/vid2vid-master/models/vid2vid_model_G.py", line 198, in inference
    fake_B = self.generate_frame_infer(real_A[self.n_scales-1-s], s)
  File "/mnt/yry/vid2vid-master/models/vid2vid_model_G.py", line 216, in generate_frame_infer
    self.fake_B_feat, self.flow_feat, self.fake_B_fg_feat, use_raw_only)    
  File "/mnt/yry/vid2vid-master/models/networks.py", line 177, in forward
    img_warp = self.resample(img_prev[:,-3:,...].cuda(gpu_id), flow).cuda(gpu_id)        
  File "/home/liuzhiqing/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/yry/vid2vid-master/models/flownet2_pytorch/networks/resample2d_package/modules/resample2d.py", line 14, in forward
    return Resample2dFunction.apply(input1_c, input2, self.kernel_size)
  File "/mnt/yry/vid2vid-master/models/flownet2_pytorch/networks/resample2d_package/functions/resample2d.py", line 19, in forward
    resample2d.Resample2d_cuda_forward(input1, input2, output, kernel_size)
  File "/home/liuzhiqing/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 197, in safe_call
    result = torch._C._safe_call(*args, **kwargs)
torch.FatalError: cuda runtime error (8) : invalid device function at Resample2d_kernel.cu:205
```

Can anybody fix it?

**Comment by martync** [comment]
Hi, 

Having the same error here. 

- Ubuntu 18.04
- Python 3.6.5
- certifi==2018.8.13
- cffi==1.11.5
- chardet==3.0.4
- dominate==2.3.1
- idna==2.7
- numpy==1.15.1
- opencv-python==3.4.2.17
- Pillow==5.2.0
- pycparser==2.18
- requests==2.19.1
- scipy==1.1.0
- six==1.11.0
- torch==0.4.1
- torchvision==0.2.1
- urllib3==1.23

**Comment by tcwang0509** [comment]
Can you first try if you can run flownet2: https://github.com/NVIDIA/flownet2-pytorch ?

**Comment by Justobe** [comment]
@switchhh Did u fix it? I met the same probem but I don't know how to fix it. Thank u in anvance.
