### ISSUE TITLE
Problem in testing

### ISSUE THREAD

**Issue by mhmtsarigul** [NVIDIA/vid2vid#125]
Hello. 

I train a model with my own dataset. But when i try to validate with test data i get the following error.

`python test.py --name mytest_256 \
--input_nc 3 --loadSize 256 --n_scales_spatial 3 --n_downsample_G 2 --use_single_G --dataroot datasets/mytest --dataset_mode mytest ` 

`------------ Options -------------
add_face_disc: False
aspect_ratio: 1.0
basic_point_only: False
batchSize: 1
checkpoints_dir: ./checkpoints
dataroot: datasets/hyper
dataset_mode: hyper
debug: False
densepose_only: False
display_id: 0
display_winsize: 512
feat_num: 3
fg: False
fg_labels: [26]
fineSize: 512
fp16: False
gpu_ids: [0]
how_many: 300
input_nc: 3
isTrain: False
label_feat: False
label_nc: 0
loadSize: 256
load_features: False
load_pretrain: 
local_rank: 0
max_dataset_size: inf
model: vid2vid
nThreads: 2
n_blocks: 9
n_blocks_local: 3
n_downsample_E: 3
n_downsample_G: 2
n_frames_G: 3
n_gpus_gen: 1
n_local_enhancers: 1
n_scales_spatial: 3
name: hyper_256
ndf: 64
nef: 32
netE: simple
netG: composite
ngf: 128
no_canny_edge: False
no_dist_map: False
no_first_img: False
no_flip: False
no_flow: False
norm: batch
ntest: inf
openpose_only: False
output_nc: 3
phase: test
random_drop_prob: 0.05
random_scale_points: False
remove_face_labels: False
resize_or_crop: scaleWidth
results_dir: ./results/
serial_batches: False
start_frame: 0
tf_log: False
use_instance: False
use_real_img: False
use_single_G: True
which_epoch: latest
-------------- End ----------------
CustomDatasetDataLoader
dataset [HyperTestDataset] was created
vid2vid
---------- Networks initialized -------------
-----------------------------------------------
./checkpoints/hyper_256/latest_net_G1.pth not exists yet!
./checkpoints/hyper_256/latest_net_G2.pth not exists yet!
Traceback (most recent call last):
  File "test.py", line 27, in <module>
    model = create_model(opt)
  File "/home/msg/vid2vid/models/models.py", line 76, in create_model
    modelG.initialize(opt)
  File "/home/msg/vid2vid/models/vid2vid_model_G.py", line 53, in initialize
    self.netG_i = self.load_single_G() if self.use_single_G else None
  File "/home/msg/vid2vid/models/vid2vid_model_G.py", line 295, in load_single_G
    netG.load_state_dict(torch.load(load_path))        
  File "/home/msg/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 777, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for GlobalGenerator:
	Missing key(s) in state_dict: "model.1.weight", "model.1.bias", "model.2.running_mean", "model.2.running_var", "model.4.weight", "model.4.bias", "model.5.running_mean", "model.5.running_var", "model.7.weight", "model.7.bias", "model.8.running_mean", "model.8.running_var", "model.10.conv_block.1.weight", "model.10.conv_block.1.bias", "model.10.conv_block.2.running_mean", "model.10.conv_block.2.running_var", "model.10.conv_block.5.weight", "model.10.conv_block.5.bias", "model.10.conv_block.6.running_mean", "model.10.conv_block.6.running_var", "model.11.conv_block.1.weight", "model.11.conv_block.1.bias", "model.11.conv_block.2.running_mean", "model.11.conv_block.2.running_var", "model.11.conv_block.5.weight", "model.11.conv_block.5.bias", "model.11.conv_block.6.running_mean", "model.11.conv_block.6.running_var", "model.12.conv_block.1.weight", "model.12.conv_block.1.bias", "model.12.conv_block.2.running_mean", "model.12.conv_block.2.running_var", "model.12.conv_block.5.weight", "model.12.conv_block.5.bias", "model.12.conv_block.6.running_mean", "model.12.conv_block.6.running_var", "model.13.conv_block.1.weight", "model.13.conv_block.1.bias", "model.13.conv_block.2.running_mean", "model.13.conv_block.2.running_var", "model.13.conv_block.5.weight", "model.13.conv_block.5.bias", "model.13.conv_block.6.running_mean", "model.13.conv_block.6.running_var", "model.14.conv_block.1.weight", "model.14.conv_block.1.bias", "model.14.conv_block.2.running_mean", "model.14.conv_block.2.running_var", "model.14.conv_block.5.weight", "model.14.conv_block.5.bias", "model.14.conv_block.6.running_mean", "model.14.conv_block.6.running_var", "model.15.conv_block.1.weight", "model.15.conv_block.1.bias", "model.15.conv_block.2.running_mean", "model.15.conv_block.2.running_var", "model.15.conv_block.5.weight", "model.15.conv_block.5.bias", "model.15.conv_block.6.running_mean", "model.15.conv_block.6.running_var", "model.16.conv_block.1.weight", "model.16.conv_block.1.bias", "model.16.conv_block.2.running_mean", "model.16.conv_block.2.running_var", "model.16.conv_block.5.weight", "model.16.conv_block.5.bias", "model.16.conv_block.6.running_mean", "model.16.conv_block.6.running_var", "model.17.conv_block.1.weight", "model.17.conv_block.1.bias", "model.17.conv_block.2.running_mean", "model.17.conv_block.2.running_var", "model.17.conv_block.5.weight", "model.17.conv_block.5.bias", "model.17.conv_block.6.running_mean", "model.17.conv_block.6.running_var", "model.18.conv_block.1.weight", "model.18.conv_block.1.bias", "model.18.conv_block.2.running_mean", "model.18.conv_block.2.running_var", "model.18.conv_block.5.weight", "model.18.conv_block.5.bias", "model.18.conv_block.6.running_mean", "model.18.conv_block.6.running_var", "model.19.weight", "model.19.bias", "model.20.running_mean", "model.20.running_var", "model.22.weight", "model.22.bias", "model.23.running_mean", "model.23.running_var", "model.26.weight", "model.26.bias". 
	Unexpected key(s) in state_dict: "model_down_seg.1.weight", "model_down_seg.1.bias", "model_down_seg.2.weight", "model_down_seg.2.bias", "model_down_seg.2.running_mean", "model_down_seg.2.running_var", "model_down_seg.2.num_batches_tracked", "model_down_seg.4.weight", "model_down_seg.4.bias", "model_down_seg.5.weight", "model_down_seg.5.bias", "model_down_seg.5.running_mean", "model_down_seg.5.running_var", "model_down_seg.5.num_batches_tracked", "model_down_seg.7.weight", "model_down_seg.7.bias", "model_down_seg.8.weight", "model_down_seg.8.bias", "model_down_seg.8.running_mean", "model_down_seg.8.running_var", "model_down_seg.8.num_batches_tracked", "model_down_seg.10.conv_block.1.weight", "model_down_seg.10.conv_block.1.bias", "model_down_seg.10.conv_block.2.weight", "model_down_seg.10.conv_block.2.bias", "model_down_seg.10.conv_block.2.running_mean", "model_down_seg.10.conv_block.2.running_var", "model_down_seg.10.conv_block.2.num_batches_tracked", "model_down_seg.10.conv_block.5.weight", "model_down_seg.10.conv_block.5.bias", "model_down_seg.10.conv_block.6.weight", "model_down_seg.10.conv_block.6.bias", "model_down_seg.10.conv_block.6.running_mean", "model_down_seg.10.conv_block.6.running_var", "model_down_seg.10.conv_block.6.num_batches_tracked", "model_down_seg.11.conv_block.1.weight", "model_down_seg.11.conv_block.1.bias", "model_down_seg.11.conv_block.2.weight", "model_down_seg.11.conv_block.2.bias", "model_down_seg.11.conv_block.2.running_mean", "model_down_seg.11.conv_block.2.running_var", "model_down_seg.11.conv_block.2.num_batches_tracked", "model_down_seg.11.conv_block.5.weight", "model_down_seg.11.conv_block.5.bias", "model_down_seg.11.conv_block.6.weight", "model_down_seg.11.conv_block.6.bias", "model_down_seg.11.conv_block.6.running_mean", "model_down_seg.11.conv_block.6.running_var", "model_down_seg.11.conv_block.6.num_batches_tracked", "model_down_seg.12.conv_block.1.weight", "model_down_seg.12.conv_block.1.bias", "model_down_seg.12.conv_block.2.weight", "model_down_seg.12.conv_block.2.bias", "model_down_seg.12.conv_block.2.running_mean", "model_down_seg.12.conv_block.2.running_var", "model_down_seg.12.conv_block.2.num_batches_tracked", "model_down_seg.12.conv_block.5.weight", "model_down_seg.12.conv_block.5.bias", "model_down_seg.12.conv_block.6.weight", "model_down_seg.12.conv_block.6.bias", "model_down_seg.12.conv_block.6.running_mean", "model_down_seg.12.conv_block.6.running_var", "model_down_seg.12.conv_block.6.num_batches_tracked", "model_down_seg.13.conv_block.1.weight", "model_down_seg.13.conv_block.1.bias", "model_down_seg.13.conv_block.2.weight", "model_down_seg.13.conv_block.2.bias", "model_down_seg.13.conv_block.2.running_mean", "model_down_seg.13.conv_block.2.running_var", "model_down_seg.13.conv_block.2.num_batches_tracked", "model_down_seg.13.conv_block.5.weight", "model_down_seg.13.conv_block.5.bias", "model_down_seg.13.conv_block.6.weight", "model_down_seg.13.conv_block.6.bias", "model_down_seg.13.conv_block.6.running_mean", "model_down_seg.13.conv_block.6.running_var", "model_down_seg.13.conv_block.6.num_batches_tracked", "model_down_seg.14.conv_block.1.weight", "model_down_seg.14.conv_block.1.bias", "model_down_seg.14.conv_block.2.weight", "model_down_seg.14.conv_block.2.bias", "model_down_seg.14.conv_block.2.running_mean", "model_down_seg.14.conv_block.2.running_var", "model_down_seg.14.conv_block.2.num_batches_tracked", "model_down_seg.14.conv_block.5.weight", "model_down_seg.14.conv_block.5.bias", "model_down_seg.14.conv_block.6.weight", "model_down_seg.14.conv_block.6.bias", "model_down_seg.14.conv_block.6.running_mean", "model_down_seg.14.conv_block.6.running_var", "model_down_seg.14.conv_block.6.num_batches_tracked", "model_down_img.1.weight", "model_down_img.1.bias", "model_down_img.2.weight", "model_down_img.2.bias", "model_down_img.2.running_mean", "model_down_img.2.running_var", "model_down_img.2.num_batches_tracked", "model_down_img.4.weight", "model_down_img.4.bias", "model_down_img.5.weight", "model_down_img.5.bias", "model_down_img.5.running_mean", "model_down_img.5.running_var", "model_down_img.5.num_batches_tracked", "model_down_img.7.weight", "model_down_img.7.bias", "model_down_img.8.weight", "model_down_img.8.bias", "model_down_img.8.running_mean", "model_down_img.8.running_var", "model_down_img.8.num_batches_tracked", "model_down_img.10.conv_block.1.weight", "model_down_img.10.conv_block.1.bias", "model_down_img.10.conv_block.2.weight", "model_down_img.10.conv_block.2.bias", "model_down_img.10.conv_block.2.running_mean", "model_down_img.10.conv_block.2.running_var", "model_down_img.10.conv_block.2.num_batches_tracked", "model_down_img.10.conv_block.5.weight", "model_down_img.10.conv_block.5.bias", "model_down_img.10.conv_block.6.weight", "model_down_img.10.conv_block.6.bias", "model_down_img.10.conv_block.6.running_mean", "model_down_img.10.conv_block.6.running_var", "model_down_img.10.conv_block.6.num_batches_tracked", "model_down_img.11.conv_block.1.weight", "model_down_img.11.conv_block.1.bias", "model_down_img.11.conv_block.2.weight", "model_down_img.11.conv_block.2.bias", "model_down_img.11.conv_block.2.running_mean", "model_down_img.11.conv_block.2.running_var", "model_down_img.11.conv_block.2.num_batches_tracked", "model_down_img.11.conv_block.5.weight", "model_down_img.11.conv_block.5.bias", "model_down_img.11.conv_block.6.weight", "model_down_img.11.conv_block.6.bias", "model_down_img.11.conv_block.6.running_mean", "model_down_img.11.conv_block.6.running_var", "model_down_img.11.conv_block.6.num_batches_tracked", "model_down_img.12.conv_block.1.weight", "model_down_img.12.conv_block.1.bias", "model_down_img.12.conv_block.2.weight", "model_down_img.12.conv_block.2.bias", "model_down_img.12.conv_block.2.running_mean", "model_down_img.12.conv_block.2.running_var", "model_down_img.12.conv_block.2.num_batches_tracked", "model_down_img.12.conv_block.5.weight", "model_down_img.12.conv_block.5.bias", "model_down_img.12.conv_block.6.weight", "model_down_img.12.conv_block.6.bias", "model_down_img.12.conv_block.6.running_mean", "model_down_img.12.conv_block.6.running_var", "model_down_img.12.conv_block.6.num_batches_tracked", "model_down_img.13.conv_block.1.weight", "model_down_img.13.conv_block.1.bias", "model_down_img.13.conv_block.2.weight", "model_down_img.13.conv_block.2.bias", "model_down_img.13.conv_block.2.running_mean", "model_down_img.13.conv_block.2.running_var", "model_down_img.13.conv_block.2.num_batches_tracked", "model_down_img.13.conv_block.5.weight", "model_down_img.13.conv_block.5.bias", "model_down_img.13.conv_block.6.weight", "model_down_img.13.conv_block.6.bias", "model_down_img.13.conv_block.6.running_mean", "model_down_img.13.conv_block.6.running_var", "model_down_img.13.conv_block.6.num_batches_tracked", "model_down_img.14.conv_block.1.weight", "model_down_img.14.conv_block.1.bias", "model_down_img.14.conv_block.2.weight", "model_down_img.14.conv_block.2.bias", "model_down_img.14.conv_block.2.running_mean", "model_down_img.14.conv_block.2.running_var", "model_down_img.14.conv_block.2.num_batches_tracked", "model_down_img.14.conv_block.5.weight", "model_down_img.14.conv_block.5.bias", "model_down_img.14.conv_block.6.weight", "model_down_img.14.conv_block.6.bias", "model_down_img.14.conv_block.6.running_mean", "model_down_img.14.conv_block.6.running_var", "model_down_img.14.conv_block.6.num_batches_tracked", "model_res_img.0.conv_block.1.weight", "model_res_img.0.conv_block.1.bias", "model_res_img.0.conv_block.2.weight", "model_res_img.0.conv_block.2.bias", "model_res_img.0.conv_block.2.running_mean", "model_res_img.0.conv_block.2.running_var", "model_res_img.0.conv_block.2.num_batches_tracked", "model_res_img.0.conv_block.5.weight", "model_res_img.0.conv_block.5.bias", "model_res_img.0.conv_block.6.weight", "model_res_img.0.conv_block.6.bias", "model_res_img.0.conv_block.6.running_mean", "model_res_img.0.conv_block.6.running_var", "model_res_img.0.conv_block.6.num_batches_tracked", "model_res_img.1.conv_block.1.weight", "model_res_img.1.conv_block.1.bias", "model_res_img.1.conv_block.2.weight", "model_res_img.1.conv_block.2.bias", "model_res_img.1.conv_block.2.running_mean", "model_res_img.1.conv_block.2.running_var", "model_res_img.1.conv_block.2.num_batches_tracked", "model_res_img.1.conv_block.5.weight", "model_res_img.1.conv_block.5.bias", "model_res_img.1.conv_block.6.weight", "model_res_img.1.conv_block.6.bias", "model_res_img.1.conv_block.6.running_mean", "model_res_img.1.conv_block.6.running_var", "model_res_img.1.conv_block.6.num_batches_tracked", "model_res_img.2.conv_block.1.weight", "model_res_img.2.conv_block.1.bias", "model_res_img.2.conv_block.2.weight", "model_res_img.2.conv_block.2.bias", "model_res_img.2.conv_block.2.running_mean", "model_res_img.2.conv_block.2.running_var", "model_res_img.2.conv_block.2.num_batches_tracked", "model_res_img.2.conv_block.5.weight", "model_res_img.2.conv_block.5.bias", "model_res_img.2.conv_block.6.weight", "model_res_img.2.conv_block.6.bias", "model_res_img.2.conv_block.6.running_mean", "model_res_img.2.conv_block.6.running_var", "model_res_img.2.conv_block.6.num_batches_tracked", "model_res_img.3.conv_block.1.weight", "model_res_img.3.conv_block.1.bias", "model_res_img.3.conv_block.2.weight", "model_res_img.3.conv_block.2.bias", "model_res_img.3.conv_block.2.running_mean", "model_res_img.3.conv_block.2.running_var", "model_res_img.3.conv_block.2.num_batches_tracked", "model_res_img.3.conv_block.5.weight", "model_res_img.3.conv_block.5.bias", "model_res_img.3.conv_block.6.weight", "model_res_img.3.conv_block.6.bias", "model_res_img.3.conv_block.6.running_mean", "model_res_img.3.conv_block.6.running_var", "model_res_img.3.conv_block.6.num_batches_tracked", "model_up_img.0.weight", "model_up_img.0.bias", "model_up_img.1.weight", "model_up_img.1.bias", "model_up_img.1.running_mean", "model_up_img.1.running_var", "model_up_img.1.num_batches_tracked", "model_up_img.3.weight", "model_up_img.3.bias", "model_up_img.4.weight", "model_up_img.4.bias", "model_up_img.4.running_mean", "model_up_img.4.running_var", "model_up_img.4.num_batches_tracked", "model_final_img.1.weight", "model_final_img.1.bias", "model_res_flow.0.conv_block.1.weight", "model_res_flow.0.conv_block.1.bias", "model_res_flow.0.conv_block.2.weight", "model_res_flow.0.conv_block.2.bias", "model_res_flow.0.conv_block.2.running_mean", "model_res_flow.0.conv_block.2.running_var", "model_res_flow.0.conv_block.2.num_batches_tracked", "model_res_flow.0.conv_block.5.weight", "model_res_flow.0.conv_block.5.bias", "model_res_flow.0.conv_block.6.weight", "model_res_flow.0.conv_block.6.bias", "model_res_flow.0.conv_block.6.running_mean", "model_res_flow.0.conv_block.6.running_var", "model_res_flow.0.conv_block.6.num_batches_tracked", "model_res_flow.1.conv_block.1.weight", "model_res_flow.1.conv_block.1.bias", "model_res_flow.1.conv_block.2.weight", "model_res_flow.1.conv_block.2.bias", "model_res_flow.1.conv_block.2.running_mean", "model_res_flow.1.conv_block.2.running_var", "model_res_flow.1.conv_block.2.num_batches_tracked", "model_res_flow.1.conv_block.5.weight", "model_res_flow.1.conv_block.5.bias", "model_res_flow.1.conv_block.6.weight", "model_res_flow.1.conv_block.6.bias", "model_res_flow.1.conv_block.6.running_mean", "model_res_flow.1.conv_block.6.running_var", "model_res_flow.1.conv_block.6.num_batches_tracked", "model_res_flow.2.conv_block.1.weight", "model_res_flow.2.conv_block.1.bias", "model_res_flow.2.conv_block.2.weight", "model_res_flow.2.conv_block.2.bias", "model_res_flow.2.conv_block.2.running_mean", "model_res_flow.2.conv_block.2.running_var", "model_res_flow.2.conv_block.2.num_batches_tracked", "model_res_flow.2.conv_block.5.weight", "model_res_flow.2.conv_block.5.bias", "model_res_flow.2.conv_block.6.weight", "model_res_flow.2.conv_block.6.bias", "model_res_flow.2.conv_block.6.running_mean", "model_res_flow.2.conv_block.6.running_var", "model_res_flow.2.conv_block.6.num_batches_tracked", "model_res_flow.3.conv_block.1.weight", "model_res_flow.3.conv_block.1.bias", "model_res_flow.3.conv_block.2.weight", "model_res_flow.3.conv_block.2.bias", "model_res_flow.3.conv_block.2.running_mean", "model_res_flow.3.conv_block.2.running_var", "model_res_flow.3.conv_block.2.num_batches_tracked", "model_res_flow.3.conv_block.5.weight", "model_res_flow.3.conv_block.5.bias", "model_res_flow.3.conv_block.6.weight", "model_res_flow.3.conv_block.6.bias", "model_res_flow.3.conv_block.6.running_mean", "model_res_flow.3.conv_block.6.running_var", "model_res_flow.3.conv_block.6.num_batches_tracked", "model_up_flow.0.weight", "model_up_flow.0.bias", "model_up_flow.1.weight", "model_up_flow.1.bias", "model_up_flow.1.running_mean", "model_up_flow.1.running_var", "model_up_flow.1.num_batches_tracked", "model_up_flow.3.weight", "model_up_flow.3.bias", "model_up_flow.4.weight", "model_up_flow.4.bias", "model_up_flow.4.running_mean", "model_up_flow.4.running_var", "model_up_flow.4.num_batches_tracked", "model_final_flow.1.weight", "model_final_flow.1.bias", "model_final_w.1.weight", "model_final_w.1.bias". `

**Comment by jiangzhubo** [comment]
i have same issue, do you solve it @mhmtsarigul

**Comment by pranavraikote** [comment]
@mhmtsarigul @jiaxianhua 
The way to solve this is, giving the path which has all the checkpoints, the error at the beginning says, latest checkpoints not found, the parameter --name path/to/checckpoints/ should point correctly to the folder where the checkpoints are present (stored while training)
