### ISSUE TITLE
no module named channelnorm_cuda

### ISSUE THREAD

**Issue by venkat8900** [NVIDIA/vid2vid#131]
ran this code on colab  :   !bash ./scripts/face/train_512.sh
And its showing me the following error. Please help me to resolve this

Traceback (most recent call last):
  File "train.py", line 148, in <module>
    train()
  File "train.py", line 28, in train
    models = create_model(opt)
  File "/content/drive/My Drive/Colab Notebooks/pix2pix_video_synthesis_NVDIA/vid2vid/models/models.py", line 79, in create_model
    flowNet.initialize(opt)        
  File "/content/drive/My Drive/Colab Notebooks/pix2pix_video_synthesis_NVDIA/vid2vid/models/flownet.py", line 14, in initialize
    from .flownet2_pytorch import models as flownet2_models
  File "/content/drive/My Drive/Colab Notebooks/pix2pix_video_synthesis_NVDIA/vid2vid/models/flownet2_pytorch/models.py", line 9, in <module>
    from .networks.channelnorm_package.channelnorm import ChannelNorm
  File "/content/drive/My Drive/Colab Notebooks/pix2pix_video_synthesis_NVDIA/vid2vid/models/flownet2_pytorch/networks/channelnorm_package/channelnorm.py", line 3, in <module>
    import channelnorm_cuda
ModuleNotFoundError: No module named 'channelnorm_cuda'

**Comment by sheiun** [comment]
```bash
cd models/networks/flownet2_pytorch/networks/channelnorm_package

python setup.py build
python setup.py install
```

**Comment by kartikJ-9** [comment]
> ```shell
> cd models/networks/flownet2_pytorch/networks/channelnorm_package
> 
> python setup.py build
> python setup.py install
> ```

I tried as  you suggested, but still the same error is coming. I am trying to implement, few shot vid2vid in google colab. But, the same error is coming.
