### ISSUE TITLE
What is required to use on windows ? 

### ISSUE THREAD

**Issue by slender9168** [NVIDIA/vid2vid#44]
Hi,
The requirements state  "mac or linux",
how can i run it on windows ?

**Comment by pshah123** [comment]
I've played around a lot with this, I don't think it is possible to run it natively in Windows. However you can try out the dockerfile, if you have Windows 10 Pro (which supports hyper-v and therefore docker CE and nvidia-docker).

**Comment by hyhouyong** [comment]
> Hi,
> The requirements state "mac or linux",
> how can i run it on windows ?

I think if you have gpu ,toch and cuda,you would run it on windows.I run it by cpu without  cuda.The result shows as follows.
python test.py --name edge2face_512 --dataroot datasets/face/ --dataset_mode face --input_nc 15 --loadSize 512 --use_single_G --gpu_id=-1

------------ Options -------------
add_face_disc: False
aspect_ratio: 1.0
basic_point_only: False
batchSize: 1
checkpoints_dir: ./checkpoints
dataroot: datasets/face/
dataset_mode: face
debug: False
densepose_only: False
display_id: 0
display_winsize: 512
feat_num: 3
fg: False
fg_labels: [26]
fineSize: 512
gpu_ids: []
how_many: 300
input_nc: 15
isTrain: False
label_feat: False
label_nc: 0
loadSize: 512
load_features: False
load_pretrain:
max_dataset_size: inf
model: vid2vid
nThreads: 2
n_blocks: 9
n_blocks_local: 3
n_downsample_E: 3
n_downsample_G: 3
n_frames_G: 3
n_gpus_gen: 0
n_local_enhancers: 1
n_scales_spatial: 1
name: edge2face_512
ndf: 64
nef: 32
netE: simple
netG: composite
ngf: 128
no_canny_edge: False
no_dist_map: False
no_first_img: False
no_flip: False
no_flow: False
norm: batch
ntest: inf
openpose_only: False
output_nc: 3
phase: test
random_drop_prob: 0.05
random_scale_points: False
remove_face_labels: False
resize_or_crop: scaleWidth
results_dir: ./results/
serial_batches: False
start_frame: 0
tf_log: False
use_instance: False
use_real_img: False
use_single_G: True
which_epoch: latest
-------------- End ----------------
CustomDatasetDataLoader
dataset [FaceDataset] was created
vid2vid
Traceback (most recent call last):
  File "test.py", line 25, in <module>
    model = create_model(opt)
  File "C:\Users\Administrator\Desktop\vid2vid-master\vid2vid-master\models\models.py", line 7, in create_model
    from .vid2vid_model_G import Vid2VidModelG
  File "C:\Users\Administrator\Desktop\vid2vid-master\vid2vid-master\models\vid2vid_model_G.py", line 13, in <module>
    from . import networks
  File "C:\Users\Administrator\Desktop\vid2vid-master\vid2vid-master\models\networks.py", line 12, in <module>
    from .flownet2_pytorch.networks.resample2d_package.resample2d import Resample2d
  File "C:\Users\Administrator\Desktop\vid2vid-master\vid2vid-master\models\flownet2_pytorch\networks\resample2d_package\resample2d.py", line 3, in <module>
    import resample2d_cuda
ModuleNotFoundError: No module named 'resample2d_cuda'
