### ISSUE TITLE
Training error: no such file ../FlowNet2_checkpoint.pth.tar

### ISSUE THREAD

**Issue by nfrik** [NVIDIA/vid2vid#49]
Awesome project, but I get training error:

Running the following script
`bash ./scripts/face/train_g1_256.sh`

Results in the following error:
```
root@d8a34002c74c:/home/vid2vid# bash ./scripts/face/train_g1_256.sh
------------ Options -------------
TTUR: False
add_face_disc: False
batchSize: 1
beta1: 0.5
checkpoints_dir: ./checkpoints
continue_train: False
dataroot: datasets/face/
dataset_mode: face
debug: False
densepose_only: False
display_freq: 100
display_id: 0
display_winsize: 512
feat_num: 3
fg: False
fg_labels: [26]
fineSize: 512
gan_mode: ls
gpu_ids: [0]
input_nc: 15
isTrain: True
label_feat: False
label_nc: 0
lambda_F: 10.0
lambda_T: 10.0
lambda_feat: 10.0
loadSize: 256
load_features: False
load_pretrain:
lr: 0.0002
max_dataset_size: inf
max_frames_backpropagate: 1
max_frames_per_gpu: 6
max_t_step: 1
model: vid2vid
nThreads: 2
n_blocks: 9
n_blocks_local: 3
n_downsample_E: 3
n_downsample_G: 3
n_frames_D: 3
n_frames_G: 3
n_frames_total: 12
n_gpus_gen: 1
n_layers_D: 3
n_local_enhancers: 1
n_scales_spatial: 1
n_scales_temporal: 3
name: edge2face_256_g1
ndf: 64
nef: 32
netE: simple
netG: composite
ngf: 64
niter: 20
niter_decay: 20
niter_fix_global: 0
niter_step: 5
no_canny_edge: False
no_dist_map: False
no_first_img: False
no_flip: False
no_flow: False
no_ganFeat: False
no_html: False
no_vgg: False
norm: batch
num_D: 2
openpose_only: False
output_nc: 3
phase: train
pool_size: 1
print_freq: 100
random_drop_prob: 0.2
remove_face_labels: False
resize_or_crop: scaleWidth
save_epoch_freq: 1
save_latest_freq: 1000
serial_batches: False
tf_log: False
use_instance: False
use_single_G: False
which_epoch: latest
-------------- End ----------------
CustomDatasetDataLoader
dataset [FaceDataset] was created
#training videos = 8
vid2vid
---------- Networks initialized -------------
-----------------------------------------------
---------- Networks initialized -------------
-----------------------------------------------
Traceback (most recent call last):
  File "train.py", line 295, in <module>
    train()
  File "train.py", line 36, in train
    modelG, modelD, flowNet = create_model(opt)
  File "/home/vid2vid/models/models.py", line 22, in create_model
    flowNet.initialize(opt)
  File "/home/vid2vid/models/flownet.py", line 19, in initialize
    checkpoint = torch.load('models/flownet2_pytorch/FlowNet2_checkpoint.pth.tar')
  File "/usr/local/lib/python2.7/dist-packages/torch/serialization.py", line 356, in load
    f = open(f, 'rb')
IOError: [Errno 2] No such file or directory: 'models/flownet2_pytorch/FlowNet2_checkpoint.pth.tar'
```
Looks like checkpoint file is missing.

**Comment by nfrik** [comment]
Had to run this script to get the model:
python scripts/download_models_flownet2.py
