### ISSUE TITLE
ModuleNotFoundError: No module named 'models.flownet2_pytorch.networks.resample2d_package._ext'

### ISSUE THREAD

**Issue by jiapei100** [NVIDIA/vid2vid#69]
Failed to test **vid2vid**...

```
➜  vid2vid git:(master) python test.py --name label2city_2048 --label_nc 35 --loadSize 2048 --n_scales_spatial 3 --use_instance --fg --use_single_G
------------ Options -------------
add_face_disc: False
aspect_ratio: 1.0
batchSize: 1
checkpoints_dir: ./checkpoints
dataroot: datasets/Cityscapes/
dataset_mode: temporal
debug: False
densepose_only: False
display_id: 0
display_winsize: 512
feat_num: 3
fg: True
fg_labels: [26]
fineSize: 512
gpu_ids: [0]
how_many: 300
input_nc: 3
isTrain: False
label_feat: False
label_nc: 35
loadSize: 2048
load_features: False
load_pretrain: 
max_dataset_size: inf
model: vid2vid
nThreads: 2
n_blocks: 9
n_blocks_local: 3
n_downsample_E: 3
n_downsample_G: 3
n_frames_G: 3
n_gpus_gen: 1
n_local_enhancers: 1
n_scales_spatial: 3
name: label2city_2048
ndf: 64
nef: 32
netE: simple
netG: composite
ngf: 128
no_canny_edge: False
no_dist_map: False
no_first_img: False
no_flip: False
no_flow: False
norm: batch
ntest: inf
openpose_only: False
output_nc: 3
phase: test
random_drop_prob: 0.2
remove_face_labels: False
resize_or_crop: scaleWidth
results_dir: ./results/
serial_batches: False
start_frame: 0
tf_log: False
use_instance: True
use_real_img: False
use_single_G: True
which_epoch: latest
-------------- End ----------------
CustomDatasetDataLoader
dataset [TestDataset] was created
vid2vid
Traceback (most recent call last):
  File "test.py", line 25, in <module>
    model = create_model(opt)
  File "....../vid2vid/models/models.py", line 7, in create_model
    from .vid2vid_model_G import Vid2VidModelG
  File "....../vid2vid/models/vid2vid_model_G.py", line 13, in <module>
    from . import networks
  File "....../vid2vid/models/networks.py", line 12, in <module>
    from .flownet2_pytorch.networks.resample2d_package.resample2d import Resample2d
ModuleNotFoundError: No module named 'models.flownet2_pytorch'
```

**Comment by dhayaiit** [comment]
go to /vid2vid/models/flownet2_pytorch/networks/resample2d_package and do

python3 setup.py build
sudo python3 setup.py install

**Comment by ezrabest** [comment]
I have the exactly same error, tried you solution 
Got the same error again

**Comment by ezrabest** [comment]
Update: Changing destination folder solved this issue, 
now the new issue is
---------- Networks initialized -------------
-----------------------------------------------
```
./checkpoints/label2city_2048/latest_net_G0.pth not exists yet!
Traceback (most recent call last):
  File "test.py", line 25, in <module>
    model = create_model(opt)
  File "/workspace/AI/vid2vid/models/models.py", line 19, in create_model
    modelG.initialize(opt)
  File "/workspace/AI/vid2vid/models/vid2vid_model_G.py", line 51, in initialize
    self.load_network(getattr(self, 'netG'+str(s)), 'G'+str(s), opt.which_epoch, opt.load_pretrain)
  File "/workspace/AI/vid2vid/models/base_model.py", line 70, in load_network
    raise('Generator must exist!')
TypeError: exceptions must derive from BaseException
```

**Comment by guancheng817** [comment]
> ## Update: Changing destination folder solved this issue,
> now the new issue is
> ---------- Networks initialized -------------
> ```
> ./checkpoints/label2city_2048/latest_net_G0.pth not exists yet!
> Traceback (most recent call last):
>   File "test.py", line 25, in <module>
>     model = create_model(opt)
>   File "/workspace/AI/vid2vid/models/models.py", line 19, in create_model
>     modelG.initialize(opt)
>   File "/workspace/AI/vid2vid/models/vid2vid_model_G.py", line 51, in initialize
>     self.load_network(getattr(self, 'netG'+str(s)), 'G'+str(s), opt.which_epoch, opt.load_pretrain)
>   File "/workspace/AI/vid2vid/models/base_model.py", line 70, in load_network
>     raise('Generator must exist!')
> TypeError: exceptions must derive from BaseException
> ```

have u ever solved the issue? I met a same issue..

**Comment by ezrabest** [comment]
nope :(

**Comment by jiapei100** [comment]
@ezrabest @guancheng817 @dhayaiit 

Please refer to my NEW issue: https://github.com/NVIDIA/vid2vid/issues/86
