### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'args'

### ISSUE THREAD

**Issue by Infinitehj** [NVIDIA/vid2vid#9]
I have compiled flownet_pytorch with python 3.6, pytorch 0.4.0.

When I run ./scripts/train_256_g1.sh , i.e.
`python train.py --name label2city_256 --loadSize 256 --use_instance --n_downsample_G 2 --num_D 1 --max_frames_per_gpu 6 --n_frames_total 6`
 I got this error:
`
Traceback (most recent call last):
  File "train.py", line 273, in <module>
    train()
  File "train.py", line 31, in train
    modelG, modelD, flowNet = create_model(opt)
  File "/home/iedl/h84104067/vid2vid-master/models/models.py", line 22, in create_model
    flowNet.initialize(opt)
  File "/home/iedl/h84104067/vid2vid-master/models/flownet.py", line 19, in initialize
    self.flowNet = flownet2_tools.module_to_dict(flownet2_models)['FlowNet2']().cuda(self.gpu_ids[0])
TypeError: __init__() missing 1 required positional argument: 'args'`

Why? Who can tell me how to solve it?

**Comment by QinZibo** [comment]
I have the same problem. And my python version is python3.5, pytorch version is 0.4.0.

**Comment by tcwang0509** [comment]
Did you download FlowNet2 by using the included script? My version is a little different from the official version now.

**Comment by Infinitehj** [comment]
@tcwang0509  Thanks a lot. It has been solved by downloading FlowNet2 by using the included script.
