### ISSUE TITLE
run python scripts/download_datasets.py

### ISSUE THREAD

**Issue by xujin1184104394** [NVIDIA/vid2vid#92]
Traceback (most recent call last):
  File "scripts/download_datasets.py", line 9, in <module>
    download_file_from_google_drive(file_id, destination) 
  File "/home1/code/vid2vid/scripts/download_gdrive.py", line 6, in download_file_from_google_drive
    response = session.get(URL, params = { 'id' : id }, stream = True)
  File "/home/xujin/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/home/xujin/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/xujin/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/xujin/anaconda2/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='docs.google.com', port=443): Max retries exceeded with url: /uc?export=download&id=1rPcbnanuApZeo2uc7h55OneBkbcFCnnf (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fe74b1cdd50>: Failed to establish a new connection: [Errno 101] Network is unreachable',))

**Comment by momo1986** [comment]
Hello,

Same issue from China Mainland.

As you know, GFW is the emperor here.

Can you give a google-driver address directly.

Thanks & regards!

**Comment by danielkaifeng** [comment]
Could anyone kindly share alternative download link?
Many thanks.

**Comment by daooshee** [comment]
Hi, [https://docs.google.com/uc?id=1rPcbnanuApZeo2uc7h55OneBkbcFCnnf](https://docs.google.com/uc?id=1rPcbnanuApZeo2uc7h55OneBkbcFCnnf) seems to be the direct download link.

**Comment by NjuHaoZhang** [comment]
@daooshee it is work, thank you very much. why not  [https://docs.google.com/uc?export=download&id=1rPcbnanuApZeo2uc7h55OneBkbcFCnnf](https://docs.google.com/uc?export=download&id=1rPcbnanuApZeo2uc7h55OneBkbcFCnnf) ? I found the link to work as follows: [https://docs.google.com/uc?export=download&confirm=40Vc&id=1rPcbnanuApZeo2uc7h55OneBkbcFCnnf](https://docs.google.com/uc?export=download&confirm=40Vc&id=1rPcbnanuApZeo2uc7h55OneBkbcFCnnf)

**Comment by NjuHaoZhang** [comment]
@daooshee computer network is important, hahhh
